sudo: required

services:
  - docker

script:
  - docker build --iidfile iid .
  - docker run -v $(pwd)/goss.yaml:/goss.yaml $(cat iid) sh -c 'curl -fsSL https://goss.rocks/install | sh; goss validate'

after_success:
  - LATEST_VERSION=$(docker run oxeva/jslint:latest jslint --version | awk '{print $3}')
  - JSLINT_VERSION=$(docker run $(cat iid) jslint --version | awk '{print $3}')
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag $(cat iid) oxeva/jslint:$JSLINT_VERSION
  - docker tag $(cat iid) oxeva/jslint:$(echo $JSLINT_VERSION | cut -d. -f 1,2)
  - if [ "$(echo -e "$LATEST_VERSION\n$JSLINT_VERSION" | sort -V | head -n1)" == "$LATEST_VERSION" ]; then
    docker tag $(cat iid) oxeva/jslint:latest
    fi
  - docker push oxeva/jslint
